title: KMK HEOR
remote_theme: pmarsceill/just-the-docs

exclude: ["README.md"]

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Aux links for the upper right navigation
aux_links:
  "KMK Consulting:
    - "https://kmkconsultinginc.com/"
aux_links_new_tab: true

# Color scheme
color_scheme: dark
